name: TrollBox

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: TrollBox
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        run: ./build.command
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TrollBox.tipa
          path: /Users/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/build/TrollBox.tipa
